fedora_task:
  container:
    image: fedora:latest
    cpu: 4
    memory: 2Gb
  install_script:
    - dnf update -y
    - dnf install -y cmake make gcc diffutils python-unversioned-command
          GraphicsMagick SDL2-devel libpng-devel zlib-devel portaudio-devel
  script:
    - mkdir build
    - cd build
    - ../configure --enable-small-mem --disable-dsp
                  --enable-werror --enable-debug || { cat config.log; exit 1; }
    - make -j4
    - ctest -j4 || { cat Testing/Temporary/LastTest.log; exit 1; }

freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-1
    cpu: 4
    memory: 4G
  install_script:
    - pkg update
    - pkg install -y pkgconf cmake gmake GraphicsMagick png
          devel/sdl20 devel/libedit
  script:
    - ./configure --enable-debug || { cat config.log; exit 1; }
    - gmake -j4
    - gmake test || { cat Testing/Temporary/LastTest.log; exit 1; }

macos_task:
  osx_instance:
    image: catalina-base
  install_script:
    - brew install cmake sdl2 libpng make tidy-html5 imagemagick
  script:
    - export PATH=/usr/local/bin:$PATH
    - ./configure --disable-osx-bundle --enable-debug
      || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake test || { cat Testing/Temporary/LastTest.log; exit 1; }

cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
    cpu: 4
    memory: 4G
  env:
    BE: cygwin-gcc
  install_script:
    - choco install -y --no-progress cygwin
    - C:\tools\cygwin\cygwinsetup.exe -q -P
        make,cmake,gcc-core,pkg-config,zlib-devel,libSDL2-devel,libpng-devel
  script:
    - C:\tools\cygwin\bin\bash.exe -lc "cd '%cd%' ;
       CFLAGS='-Werror -Wno-error=char-subscripts' cmake -G 'Unix Makefiles' ."
    - C:\tools\cygwin\bin\bash.exe -lc "cd '%cd%' ; make -j4"
  test_script:
    - C:\tools\cygwin\bin\bash.exe -lc "cd '%cd%' ; ctest -j4"

visualstudio_task:
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
    cpu: 4
    memory: 4G
  choco_cache:
    folder: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey
  install_script:
    - choco install -y --no-progress visualstudio2017community
        visualstudio2017-workload-vctools
    # Keep the log and temporary files out of the cache:
    - del C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\*.log
    - del C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\*.tmp
    - del C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\windowssdk\*.log
    # Install the required libraries and headers:
    - curl -O "https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip"
    - powershell -command "Expand-Archive -Force '%cd%\SDL2-devel-2.0.14-VC.zip' '%cd%'"
    - curl -O https://raw.githubusercontent.com/barrysteyn/scrypt-windows/master/win/include/unistd.h
    - curl -O https://raw.githubusercontent.com/tronkko/dirent/master/include/dirent.h
    - echo // > getopt.h
  script:
    - cmake -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE="Release"
        -DSDL2_INCLUDE_DIR="%cd%\SDL2-2.0.14\include"
        -DSDL2_LIBRARY="%cd%\SDL2-2.0.14\lib\x86\SDL2.lib"
        -DSDL2MAIN_LIBRARY="%cd%\SDL2-2.0.14\lib\x86\SDL2main.lib" .
    - cmake --build . --verbose --target ALL_BUILD --config Release -j4
  test_script:
    - ctest -C Release
