fedora_task:
  container:
    image: fedora:latest
    cpu: 4
    memory: 2Gb
  install_script:
    - dnf update -y
    - dnf install -y cmake make gcc diffutils python-unversioned-command
          capstone-devel GraphicsMagick SDL2-devel libpng-devel zlib-devel tidy
  script:
    - mkdir build
    - cd build
    - ../configure --enable-small-mem --disable-dsp
                  --enable-werror --enable-debug || { cat config.log; exit 1; }
    - make -j4
    - ctest -j4 || { cat Testing/Temporary/LastTest.log; exit 1; }

freebsd_task:
  freebsd_instance:
    image_family: freebsd-13-0
    cpu: 4
    memory: 4G
  install_script:
    - pkg update
    - pkg install -y pkgconf cmake gmake capstone4 GraphicsMagick png
          devel/sdl20 devel/libedit
  script:
    - ./configure --enable-debug || { cat config.log; exit 1; }
    - gmake -j4
    - gmake test || { cat Testing/Temporary/LastTest.log; exit 1; }

macos_task:
  osx_instance:
    image: big-sur-base
  install_script:
    - brew update
    - brew install sdl2 libpng make tidy-html5 imagemagick
  script:
    - export PATH=/usr/local/bin:$PATH
    - ./configure --disable-osx-bundle --enable-debug
      || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake test || { cat Testing/Temporary/LastTest.log; exit 1; }

cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
    cpu: 4
    memory: 4G
  env:
    BE: cygwin-gcc
  install_script:
    - choco install -y --no-progress cygwin
    - C:\tools\cygwin\cygwinsetup.exe -q -P
        make,cmake,gcc-core,pkg-config,zlib-devel,libSDL2-devel,libpng-devel
  script:
    - C:\tools\cygwin\bin\bash.exe -lc "cd '%cd%' ;
       CFLAGS='-Werror -Wno-error=char-subscripts' cmake -G 'Unix Makefiles' ."
    - C:\tools\cygwin\bin\bash.exe -lc "cd '%cd%' ; make -j4"
  test_script:
    - C:\tools\cygwin\bin\bash.exe -lc "cd '%cd%' ; ctest -j4"

msys2_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    cpu: 4
    memory: 4G
  env:
    MSYS: winsymlinks:nativestrict
    MSYSTEM: MINGW64
    CHERE_INVOKING: 1
  choco_cache:
    folder: '%temp%\chocolatey'
  install_script:
    - choco install -y --no-progress msys2
    # Keep the log and temporary files out of the cache:
    - del %temp%\chocolatey\*.log
    - del %temp%\chocolatey\*log.txt
    - del %temp%\chocolatey\*.tmp
    # Install the required libraries:
    - C:\tools\msys64\usr\bin\bash -lc "pacman --noconfirm -S --needed
         make pkg-config diffutils
         mingw-w64-x86_64-cmake
         mingw-w64-x86_64-gcc
         mingw-w64-x86_64-SDL2
         mingw-w64-x86_64-libpng
         mingw-w64-x86_64-portmidi"
  script:
    - C:\tools\msys64\usr\bin\bash -lc "cmake -G 'MSYS Makefiles' ."
    - C:\tools\msys64\usr\bin\bash -lc "make -j4"
  test_script:
    - C:\tools\msys64\usr\bin\bash -lc "ctest"

visualstudio_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    cpu: 4
    memory: 4G
  choco_cache:
    folder: '%temp%\chocolatey'
  install_script:
    - choco install -y --no-progress cmake --install-arguments="ADD_CMAKE_TO_PATH=System"
    - choco install -y --no-progress visualstudio2019community
        visualstudio2019-workload-vctools
    # Keep the log and temporary files out of the cache:
    - del %temp%\chocolatey\*.log
    - del %temp%\chocolatey\*log.txt
    - del %temp%\chocolatey\*.tmp
    - del %temp%\chocolatey\windowssdk\*.log
    - del %temp%\chocolatey\VSLogs\*.svclog
    # Install the required libraries and headers:
    - curl -O "https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip"
    - powershell -command "Expand-Archive -Force '%cd%\SDL2-devel-2.0.14-VC.zip' '%cd%'"
    - curl -O https://raw.githubusercontent.com/barrysteyn/scrypt-windows/master/win/include/unistd.h
    - curl -O https://raw.githubusercontent.com/tronkko/dirent/master/include/dirent.h
    - echo // > getopt.h
  script:
    - refreshenv
    - cmake -G "Visual Studio 16 2019" -A X64 -DCMAKE_BUILD_TYPE="Release"
        -DSDL2_INCLUDE_DIR="%cd%\SDL2-2.0.14\include"
        -DSDL2_LIBRARY="%cd%\SDL2-2.0.14\lib\x64\SDL2.lib"
        -DSDL2MAIN_LIBRARY="%cd%\SDL2-2.0.14\lib\x64\SDL2main.lib" .
    - cmake --build . --verbose --target ALL_BUILD --config Release -j4
  test_script:
    - refreshenv
    - ctest -C Release
