# Makefile configuration for Hatari.

# Set the C compiler (e.g. gcc)
CC = gcc

# The native C compiler.
# This is normaly the same as $(CC) unless you are using a cross compiler.
HOSTCC = $(CC)

# Set flags passed to the compiler (e.g. optimization flags)
CFLAGS = -g -O2 -Wall -Wno-unused

# Set flags passed to the preprocessor (e.g. -I<include dir>)
CPPFLAGS =

# SDL-Library configuration (compiler flags and linker options) - you normally
# don't have to change this if you have correctly installed the SDL library!
SDL_CFLAGS = $(shell sdl-config --cflags)
SDL_LIBS = $(shell sdl-config --libs)


# Here you can define the default data directory for Hatari.
# The emulator looks there for the default TOS image, its font etc.
# For example you can use the local directory with "." or if you want
# a system-wide installation, use something like "/usr/share/hatari".
DATADIR = /usr/local/share/hatari/

# The executable will be installed in BINDIR
BINDIR = /usr/local/bin


# Program used for "make install"
INSTALL = install -c
INSTALL_PROGRAM = $(INSTALL) -s
INSTALL_DATA = $(INSTALL) -m 644
