#!/usr/bin/python3
#
# Utility to generate from Hatari C-code Python code for mapping
# Hatari configuration variable names and types of those variables.
#
# Copyright (C) 2012-2025 by Eero Tamminen
#
# SPDX-License-Identifier: GPL-2.0-or-later

import os, re, sys

# match first two items (variable name and type) from lines like:
# { "bConfirmQuit", Bool_Tag, &ConfigureParams.Log.bConfirmQuit }
reg = re.compile("\"([a-zA-Z0-9_]+)\",\\s*([BFIKS][a-z]+)_Tag\\s*,")

vartypes = {}
for line in sys.stdin.readlines():
    match = reg.search(line)
    if not match:
        continue
    key,value = match.groups()
    if key not in vartypes:
        vartypes[key] = value
        continue
    if vartypes[key] != value:
        print(f"ERROR: variable '{key}' already with type '{vartypes[key]}', not '{value}'!")
        sys.exit(1)

print(f"# content generated by {os.path.basename(sys.argv[0])}")
print("conftypes = {")
for key in sorted(vartypes.keys(), key=str.casefold):
    print(f"""    "{key}": "{vartypes[key]}",""")
print("}")
