#!/bin/sh
# run Hatari UI with everything possible
$0.py  -e \
--top "about,run,pause,quit" \
--panel "Keys,paste,Macro=Test,Undo=97,Help=98,Enter=114,F1=59,F2=60,F3=61,F4=62" \
--right "setup,debug,trace,Keys" \
--bottom "sound,spec512,|,fastforward,|,frameskip"
