.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "HATARI" "1" "2008-03-14" "Hatari" ""
.\" Please adjust this date whenever revising the manpage.

.SH "NAME"
Hatari \- emulateur Atari ST(e)
.SH "SYNOPSIS"
.B hatari
.RI  [options]
.RI  [diskimage]
.SH "DESCRIPTION"
Hatari est un emulateur d'Atari ST(e) pour Linux, FreeBSD, BeOS ainsi
que tout systemes d'exploitation supportant la bibliotheque SDL.
.PP
Avec Hatari vous pouvez lancer des jeux, demos ou des applications
ecrites pour l'Atari ST ou STE.
Il supporte egalement les images de disquettes les plus couramment
utilisees a savoir *.st et *.msa. Il permet aussi l'emulation de
disque dur.
.PP
Pour lancer l'emulateur une image ROM du TOS est requise. EmuTOS
est une implementation libre du TOS fournie avec Hatari.
Malheureusement cette derniere n'est pas entierement compatible avec
le TOS original donc certains programmes risquent de ne pas
fonctionner correctement. Pour cela, il est recommande d'utiliser
une ROM TOS issue d'un veritable Atari.
.SH "OPTIONS"
Les options sont classées en sous catégories:
.SH "Options générale"
.TP
.B \-h, \-\-help
affiche les options de la ligne de commande
.TP
.B \-v, \-\-version
affiche les informations sur la version
.TP 
.B \-\-confirm-quit <bool>
Whether Hatari confirms quitting
.TP
.B \-c, \-\-configfile <filename>
utilise un fichier nomme explicitement comme fichier de configuration
en lieu et place du ~/.hatari/hatari.cfg
.SH "Options d'écran
.TP
.B \-\-monitor <x>
selectionne le type de moniteur (x = mono/rgb/vga/tv)
.TP
.B \-f, \-\-fullscreen
demarre l'emulateur en mode plein ecran
.TP
.B \-w, \-\-window
demarre l'emulateur en mode fenetre
.TP
.B \-z, \-\-zoom <x>
agrandir les petites résolutions (1=non, 2=oui)
.TP
.B \-\-frameskips <x>
Saute <x> images apres chaque image affichees pour accelerer l'emulation
(0 <= x <= 8)
.TP 
.B \-\-borders <bool>
Show screen borders (for overscan demos etc)
.TP
.B \-\-spec512 <x>
Hatari uses this threshold to decide when to render a screen with
the slower but more accurate Spectrum512 screen conversion functions
(0 <= x <= 512, 0=disable)
.TP
.B \-\-bpp <bool>
Force given internal bitdepth (x=8/16/32, x=0 for autodetection).
8-bit color depth may be useful for older host computers
.SH "Options de VDI"
.TP
.B \-\-vdi\-planes <x>
utilise une resolution VDI etendue avec une profondeur de bit de <x>
(x = 1, 2 or 4)
.TP
.B \-\-vdi\-width <w>
utilise une resolution VDI etendue avec une largeur de <w> (384 <= w <= 1024)
.TP
.B \-\-vdi\-height <h>
utilise une resolution VDI etendue avec une hauteur de <h> (200 < h <= 768)
.SH "Options d'interface"
.TP
.B \-j, \-\-joystick <port>
emule le joystick ST sur le <port> 0 ou 1 avec le clavier
.TP
.B \-\-printer <file>
active le support de l'imprimante et ecrit les donnees dans le fichier <file>
.TP
.B \-\-midi <filename>
active la sortie MIDI experimentale vers un fichier mentionne par un nom
.TP
.B \-\-rs232 <filename>
active l'emulation experimentale du RS232 via un fichier/device
nomme explicitement
.SH "Options des disques"
.TP
.B \-d, \-\-harddrive <dir>
utilise <dir> comme un disque dur emule
.TP
.B \-\-acsi <file>
emule un disque dur ACSI avec un fichier image <file>
.TP
.B \-\-fastfdc <bool>
accelere l'emulation du FDC (peut entrainer des erreurs dans certains jeux ou demos)
.SH "Options de mémoire"
.TP
.B \-s, \-\-memsize <x>
fixe une quantite de memoire pour la RAM emulee, x = 1 a 14 MiB,
ou 0 pour 512 Ko
.TP
.B \-t, \-\-tos <imagefile>
specifie une image ROM TOS a utiliser
.TP
.B \-\-cartridge <imagefile>
utilise une image ROM de cartouche <file> (fonctionne uniquement si
l'emulation de disque dur et VDI etendue sont desactivee)
.TP 
.B \-\-memstate <file>
Load memory snap-shot <file>
.SH "Option du processeur"
.TP
.B \-\-cpulevel <x>
specifie un CPU (680x0) a utiliser (TOS 2.06 uniquement!!)
.TP 
.B \-\-cpuclock <x>
Set the CPU clock (8, 16 or 32 Mhz)
.TP
.B \-\-compatible <bool>
utilise le mode de compatibilite plus fidele mais plus lent
que le mode 68000
.SH "Options diverses du système"
.TP
.B \-\-machine <x>
selectionne un type de machine (x = st, ste, tt ou falcon)
.TP
.B \-\-blitter <bool>
active l'emulation du blitter
.TP
.B \-\-dsp <x>
emulation du DSP du Falcon (x = aucune, factice ou emulee)
.TP
.B \-\-sound <x>
Régle le son (x=off/low/med/hi)
.TP
.B \-\-keymap <file>
charge un fichier de refinition du clavier de <file>
.SH "Options de déboguer"
.TP
.B \-D, \-\-debug
active le deboggueur integre
.TP
.B \-\-log <file>
Sauvegarde le rapport vers le fichier <file> (peut aussi etre "stdout" ou
"stderr")
.TP
.B \-\-trace <trace1,...>
Activate debug traces, see \-\-trace help for tracing options

.SH "COMMANDS"

Les touches de raccourcis peuvent etre parametrees dans le fichier
de configurations.
Par defaut, les parametres sont:
.TP
.B AltGr + a
enregistre l'animation
.TP
.B AltGr + g
fait une capture d'ecran
.TP
.B AltGr + i
touche patron: quitte le mode plein ecran et met la fenetre en icone
.TP
.B AltGr + j
active l'emulation joystick via les touches de directions
.TP
.B AltGr + m
(active/desactive) la souris dans la fenetre
.TP
.B AltGr + r
eteint le ST (a chaud)
.TP
.B AltGr + c
eteint le ST a froid (comme le bouton original d'allumage)
.TP
.B AltGr + s
active/desactive le son
.TP
.B AltGr + q
quitte l'emulateur
.TP
.B AltGr + x
change la vitesse normale/maximum
.TP
.B AltGr + y
active/desactive l'enregistrement du son
.TP
.B AltGr + k
sauvegarde l'etat de la memoire
.TP
.B AltGr + l
restaure l'etat de la memoire
.TP
.B F11
change le mode entre plein ecran et fenetre
.TP
.B F12
active les commandes GUI de Hatari
.br
Vous pouvez avoir besoin de tenir la touche SHIFT en mode fenetre
.TP
.B Pause
Ouvrira le deboggueur, s'il etait active avec l'option \-\-debug

.SH Clavier d'Atari ST emule
Toutes les autres touches du clavier PC agissent comme celles de Atari ST
donc si vous appuyez sur ESPACE sur votre PC il en resultera sur
le clavier d'Atari ST un appuis sur la touche ESPACE. Les touches suivantes
ont une signification speciales :
.TP
.B  Alt
Agira comme la touche ALTERNATE du clavier ST
.TP
.B  left Ctrl
Agira comme la touche CONTROL du clavier ST
.TP
.B  Page Up
Emulera la touche HELP du clavier ST
.TP
.B  Page Down
Emulera la touche UNDO du clavier ST
.PP
.B AltGr
Agira comme
.B Alternate
tel sauf si vous appuyez sur les touches speciales d'Hatari.

La touche
.B right Ctrl
est utilisee comme le bouton feu d'un joystick emule
que vous aurez active precedement par l'emulation du joystick via
les touches du clavier.

Le touche de directions agiront comme les touches de directions sur
l'Atari ST tant que l'emulation du joystick par le clavier est inactive.
.SH "VOIR AUSSI"
La documentation originale du programme, habituellement
en /usr/share/doc/.
.PP
La page d'accueil d'Hatari : http://hatari.tuxfamily.org/

.SH "FICHIERS"
.TP
/etc/hatari.cfg (ou /usr/local/etc/hatari.cfg)
le fichier de configuration global d'Hatari
.TP
~/.hatari/hatari.cfg
Le fichier de configuration de l'utilisateur personnel
d'Hatari
.TP
tos.img
L'image ROM du TOS qui sera charge a partir du repertoire de donnees d'Hatari
si aucun argument n'est specifie sur la ligne de commande ou dans le fichier
de configuration.

.SH "AUTEURS"
Cette page du manuel a ete ecrite par Marco Herrn <marco@mherrn.de>,
pour le projet Debian et modifiee par la suite par Thomas Huth pour les
versions plus recentes d'Hatari

.SH "TRADUCTEUR"
Benoît TUDURI <skweek@users.sourceforge.net>
