.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "HATARI" "1" "2008-02-03" "Hatari" ""
.\" Please adjust this date whenever revising the manpage.

.SH "NAME"
hatari \- Atari ST(e) emulator
.SH "SYNOPSIS"
.B hatari
.RI  [options]
.RI  [diskimage]
.SH "DESCRIPTION"
Hatari is an Atari ST(e) emulator for Linux, FreeBSD, BeOS and other
Systems which are supported by the SDL library.
.PP
With hatari one can run games, demos or applications written for Atari
ST or Atari STE. It supports the commonly used *.st and *.msa disk
images and hard disk emulation.
.PP
To run the emulator a TOS ROM image is needed. EmuTOS, a free
implementation of TOS is shipped with hatari. Since it is not yet
fully compatible with the original TOS some programs won't run
correctly with this. Because of this it is recommended to use a TOS
ROM from a real Atari.
.SH "OPTIONS"
Hatari options are split into several categories:
.SH "General options"
.TP 
.B \-h, \-\-help
Print command line options and terminate
.TP 
.B \-v, \-\-version
Print version information and terminate
.TP 
.B \--confirm-quit <bool>
Whether Hatari confirms quitting
.SH "Display options"
.TP 
.B \-m, \-\-mono
Start in monochrome mode instead of color
.TP 
.B \-\-monitor <x>
Select monitor type (x = mono/rgb/vga/tv)
.TP 
.B \-f, \-\-fullscreen
Start the emulator in fullscreen mode
.TP 
.B \-w, \-\-window
Start the emulator in window mode
.TP 
.B \-z, \-\-zoom <x>
Zoom low resolution (1=no, 2=yes)
.TP 
.B \-\-frameskips <x>
Skip <x> frames after each displayed frame to accelerate emulation
(0 <= x <= 8)
.TP 
.B \-\-borders <bool>
Show screen borders (for overscan demos etc)
.TP 
.B \-\-bpp <bool>
Force given internal bitdepth (x=8/16, x=0 to disable). 8-bit color
depth may be useful for older host computers
.TP 
.B \-\-vdi\-planes <x>
Use extended VDI resolution with bit depth <x> (x = 1, 2 or 4)
.TP 
.B \-\-vdi\-width <w>
Use extended VDI resolution with width <w> (384 <= w <= 1024)
.TP 
.B \-\-vdi\-height <h>
Use extended VDI resolution with height <h> (200 < h <= 768)
.SH "Devices options"
.TP 
.B \-j, \-\-joystick <port>
Emulate joystick with cursor keys in given port (0-5)
.TP 
.B \-\-printer <file>
Enable printer support and write data to <file>
.TP 
.B \-\-midi <filename>
Enable experimental MIDI output to the mentioned file
.TP 
.B \-\-rs232 <filename>
Enable experimental RS232 emulation via the mentioned file/device
.SH "Disk options"
.TP 
.B \-\-acsi <file>
Emulate ACSI hard disk with an image <file>
.TP 
.B \-d, \-\-harddrive <dir>
Use <dir> as an emulated hard disk
.TP 
.B \-\-slowfdc <bool>
slow down FDC emulation (needed to make some games and demos work)
.SH "System options"
.TP 
.B \-t, \-\-tos <imagefile>
Specify TOS ROM image to use
.TP 
.B \-\-cartridge <imagefile>
Use ROM cartridge image <file> (only works if GEMDOS HD emulation and
extended VDI resolution are disabled)
.TP 
.B \-\-cpulevel <x>
Specify CPU (680x0) to use (use x >= 1 with EmuTOS or TOS >= 2.06 only!)
.TP 
.B \-\-cpuclock <x>
Set the CPU clock (8, 16 or 32 Mhz)
.TP 
.B \-\-compatible <bool>
Use a more compatible but slower 68000 CPU mode
.TP 
.B \-\-blitter <bool>
Enable blitter emulation
.TP 
.B \-\-dsp <x>
Falcon DSP emulation (x = none, dummy or emu)
.TP 
.B \-s, \-\-memsize <x>
Set amount of emulated RAM, x = 1 to 14 MiB, or 0 for 512 KiB
.TP 
.B \-\-memstate <file>
Load memory snap-shot <file>
.TP 
.B \-c, \-\-configfile <filename>
use the mentioned file as configuration file instead of ~/.hatari.cfg
.TP 
.B \-\-keymap <file>
load keyboard mapping from <file>
.TP 
.B \-\-machine <x>
select machine type (x = st, ste, tt or falcon)
.TP 
.B \-\-sound <x>
Sound quality (off/low/med/hi (off=faster))
.SH "Debug options"
.TP 
.B \-D, \-\-debug <bool>
activate the simple builtin debugger
.TP
.B \-\-log <file>
Save log to <file> (can also be "stdout" or "stderr")
.TP
.B \-\-trace <trace1,...>
Activate debug traces, see --trace help for tracing options
.SH "COMMANDS"
The shortcut keys can be configured in the configuration file.
The default settings are:
.TP
.B AltGr + a
record animation
.TP
.B AltGr + g
grab a screenshot
.TP
.B AltGr + i
boss key: leave full screen mode and iconify window
.TP
.B AltGr + j
activate joystick emulation via cursor keys
.TP
.B AltGr + m
(un-)lock the mouse into the window
.TP
.B AltGr + r
(warm) reset the ST
.TP
.B AltGr + c
coldreset the ST (same as the original power switch)
.TP
.B AltGr + s
enable/disable sound
.TP
.B AltGr + q
quit the emulator
.TP
.B AltGr + x
toggle normal/max speed
.TP
.B AltGr + y
enable/disable sound recording
.TP
.B AltGr + k
save memory snapshot
.TP
.B AltGr + l
load memory snapshot
.TP
.B F11
toggle between fullscreen and windowed mode
.TP
.B F12 
activate the hatari command GUI
.br
You may need to hold SHIFT down while in windowed mode.
.TP
.B Pause
will go to the debugger if it was activated with the -\-debug option

.SH Emulated Atari ST keyboard
All other keys on the keyboard act as the normal Atari ST keys so
pressing SPACE on your PC will result in an emulated press of the
SPACE key on the ST. The following keys have special meanings:
.TP
.B  Alt
will act as the ST's ALTERNATE key
.TP
.B  left Ctrl
will act as the ST's CONTROL key
.TP
.B  Page Up
will emulate the ST's HELP key
.TP
.B  Page Down
will emulate the ST's UNDO key
.PP
.B AltGr
will act as
.B Alternate
as well as long as you do not press it together with a Hatari hotkey
combination. 

The 
.B right Ctrl
key is used as the fire button of the emulated joystick when you turn
on joystick emulation via keyboard. 

The cursor keys will act as the cursor keys on the Atari ST as long as
joystick emulation via keyboard has been turned off.

.SH "SEE ALSO"
The main program documentation, usually in /usr/share/doc/.
.PP
The homepage of hatari: http://hatari.sourceforge.net

.SH "FILES"
.TP
/etc/hatari.cfg (or /usr/local/etc/hatari.cfg)
the global configuration file of Hatari
.TP
~/.hatari.cfg
the user's personal Hatari configuration file
.TP
tos.img
The TOS ROM image will be loaded from the data directory of Hatari unless it
is specified on the command line or the configuration file.

.SH "AUTHOR"
This manual page was written by Marco Herrn <marco@mherrn.de>, for the
Debian project and later modified by Thomas Huth to suit the latest
version of Hatari.
