.TH "ZIP2ST" "1" "2016-02-26" "Hatari" "Hatari utilities"
.SH NAME
zip2st \- convert directory or .zip archive to .st disk image
.SH SYNOPSIS
.B zip2st
.RI <directory|srcname.zip>
.RI [dstname.st]
.SH DESCRIPTION
zip2st can be used to generate Atari .st disk image from directory
and .zip archive contents.
.PP
If the destination filename is not given, it's based on the source
name, with the .zip extension removed and .st prefix added. If
\fIbasename\fP tool is present, file is saved to current directory,
otherwise to the directory where the source directory/archive is.
.PP
Any single directories (other than 'auto') within the source zip /
directory hierarchy are traversed down, to avoid adding redundant
intermediate directories to the generated disk image.
.PP
The .st disk image is a raw disk image, and can be written to a floppy
using dd(1), or converted to a .msa disk image with \fIhmsa\fP(1).
.PP
The contents of the uncompressed zip file needs to be smaller than
2.88MB (the largest floppy image size supported by Hatari).
.PP
If the source file names are longer than 8+3, use \fIatari\-convert\-dir\fP
script to convert them into Atari compatible ones.  If the files are
within a .zip archive, you need to extract them before conversion.
.PP
.SH SEE ALSO
.IR hmsa (1),
.IR atari\-convert\-dir (1),
.IR atari\-hd\-image (1),
.IR hatari (1),
.IR unzip (1),
.IR mtools (1),
.IR basename (1),
.IR dd (1).
.SH "AUTHOR"
Written by Thomas Huth <huth at tuxfamily.org> and Eero Tamminen.
.PP
This manual page was written by Teemu Hukkanen <tjhukkan at iki.fi>
for the Debian project and later modified by Eero Tamminen to
suit the latest version of Hatari.
.SH "LICENSE"
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
.SH "NO WARRANTY"
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.
