
IF (READLINE_INCLUDE_DIR)
  # Already in cache, be silent
  SET(READLINE_FIND_QUIETLY TRUE)
ENDIF (READLINE_INCLUDE_DIR)

FIND_PATH(READLINE_INCLUDE_DIR readline/readline.h)

FIND_LIBRARY(READLINE_LIBRARY NAMES readline)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(READLINE DEFAULT_MSG
                                  READLINE_LIBRARY READLINE_INCLUDE_DIR)

IF(NOT READLINE_FOUND)
  UNSET(READLINE_LIBRARY)
  UNSET(READLINE_INCLUDE_DIR)
ENDIF(NOT READLINE_FOUND)
