name: Build Hatari on macOS

on:
  push:
    branches:
    - main
    - test
    tags:
    - v*

jobs:

  macos_bundle:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6

    - name: Restore cached libraries
      id: cache-libs-restore
      uses: actions/cache/restore@v5
      with:
        path: dl_cache
        key: ${{ runner.os }}-libs-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-libs-

    - name: Prepare libraries
      run: |
        ci/macos-setup.sh

    - name: Save libraries
      if: ${{ hashFiles('libs-changed.txt') != '' }}
      id: cache-libs-save
      uses: actions/cache/save@v5
      with:
        path: dl_cache
        key: ${{ runner.os }}-libs-${{ github.run_id }}

    - name: Compile Hatari
      run: |
        ci/macos-build.sh

    - name: Publish artifact
      uses: actions/upload-artifact@v7
      with:
        path: hatari-snapshot.zip
        archive: false

  macos_cli:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v6

    - name: Install libraries via brew
      run: |
        brew update
        brew install make sdl3 capstone tidy-html5 imagemagick

    - name: Compile and test Hatari
      run: |
        export PATH=/usr/local/bin:$PATH
        ./configure --disable-osx-bundle --enable-debug \
          || { cat config.log; exit 1; }
        gmake -j$(sysctl -n hw.ncpu)
        ctest -j$(sysctl -n hw.ncpu) test \
          || { cat Testing/Temporary/LastTest.log; exit 1; }
